import Head from "next/head";
import styles from "../styles/Home.module.css";
import { getPostsMetaData } from "./api/getPostsData";

export default function Home({ postsData }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>behoney</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome!</h1>

        <p className={styles.description}></p>

        <div className={styles.grid}>
          {postsData.map((metadata) => {
            console.log(metadata);
            return (
              <a
                key={metadata.id}
                href={`/blog/${metadata.id}`}
                className={styles.card}
              >
                <h2>{metadata.title}</h2>
                <p>{metadata.description}</p>
              </a>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>Powered by Behoney</footer>
    </div>
  );
}

export async function getStaticProps() {
  const postsData = getPostsMetaData();
  return {
    props: {
      postsData: postsData,
    },
  };
}
