import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { getPostsMetaData } from "./api/getPostsData";

export default function Home({ postsData }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome!</h1>

        <p className={styles.description}>
          you are now
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {postsData.map((metadata) => {
            return (
              <a key={metadata.id} href="#" className={styles.card}>
                <h2>{metadata.title}</h2>
                <p>{metadata.description}</p>
              </a>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Behoney
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  const postsData = getPostsMetaData();
  return {
    props: {
      postsData: postsData,
    },
  };
}
